#!/bin/sh
## ~/.kube/config generator
##
## - creates ~/.kube/config file with the provided context name
## - uses authentication helper which cats token from the path given (used with volume projection)

: ${KUBE_CONTEXT:?kube context name is not provided}
: ${KUBE_TOKENPATH:?path to Kubernetes token path is not provided}

mkdir -p $HOME/.kube/bin

# ~/.kube/config
cat <<EHD > $HOME/.kube/config
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://kubernetes.default
  name: default
contexts:
- context:
    cluster: default
    user: user
  name: $KUBE_CONTEXT
current-context: $KUBE_CONTEXT
kind: Config
preferences: {}
users:
- name: user
  user:
    exec:
      command: "./bin/token"
      apiVersion: "client.authentication.k8s.io/v1beta1"
      interactiveMode: Never
EHD

# auth helper
cat <<EHD > $HOME/.kube/bin/token
#!/bin/sh
cat <<EOF
{
  "apiVersion": "client.authentication.k8s.io/v1beta1",
  "kind": "ExecCredential",
  "status": {
    "token": "$(cat $KUBE_TOKENPATH)"
  }
}
EOF
EHD

chmod 0755 $HOME/.kube/bin/token
